import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import 'bootstrap/dist/css/bootstrap.min.css';
import 'font-awesome/css/font-awesome.min.css';
import Navbar from './components/Navbar';
import Footer from "./components/Footer";
// index.js ou App.js
import { library } from '@fortawesome/fontawesome-svg-core';
import { faBars, faUser  } from '@fortawesome/free-solid-svg-icons';
import Script from 'next/script';

import styles from './page.module.css';

// Adiciona os ícones à biblioteca
library.add([faBars,faUser]);


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          <div className={styles.content}>
            {children}
          </div>
          <Footer />
          <Script
            src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.2/mdb.umd.min.js"
            strategy="beforeInteractive" // Ou use "lazyOnload" dependendo do comportamento desejado
          />
        </body>
      </html>
    </>
  );
}
